version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build: ./backend
    container_name: backend-app
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3901:3000"
    depends_on:
      - app
